name: SuperCraftBros
authors: [Double0negative, MCSG, NextInfinity, quinnshultz]
version: 1.7.2
main: org.mcsg.double0negative.supercraftbros.SuperCraftBros
commands:
  scb:
    description: Super Craft Bros
    usage: /scb (command) (args)
    aliases: [scb]
softdepend: [Vault]
